
// This file is auto-generated by gen_decoder.py

`include "decode.vh"

module DCROM # (
`include "msg_param.vh"
) (
	input [8 : 0] lookup_idx,
	output reg [IDU_ISU_decode_fu_type_len - 1 : 0] fu_type,
	output reg [IDU_ISU_decode_fu_op_len - 1 : 0] fu_op,
	output reg [IDU_ISU_decode_b_src_len - 1 : 0] b_src,
	output reg [IDU_ISU_decode_ext_type_len - 1 : 0] ext_type,
	output reg [IDU_ISU_decode_rd_sel_len - 1 : 0] rd_sel,
	output reg [IDU_ISU_decode_a_src_len - 1 : 0] a_src,
	output reg [`DE_SPECIAL_LEN - 1 : 0] de_special,
	output reg [25 : 0] mask,
	output reg [25 : 0] value
);

	always @(*) begin
		case(lookup_idx)
			/* ADD     */  {`INSTR_TYPE_SPECIAL     , 6'b100000}: fu_type = `FU_TYPE_ALU;
			/* ADDU    */  {`INSTR_TYPE_SPECIAL     , 6'b100001}: fu_type = `FU_TYPE_ALU;
			/* ADDI    */  {`INSTR_TYPE_COMMON      , 6'b001000}: fu_type = `FU_TYPE_ALU;
			/* ADDIU   */  {`INSTR_TYPE_COMMON      , 6'b001001}: fu_type = `FU_TYPE_ALU;
			/* SUB     */  {`INSTR_TYPE_SPECIAL     , 6'b100010}: fu_type = `FU_TYPE_ALU;
			/* SUBU    */  {`INSTR_TYPE_SPECIAL     , 6'b100011}: fu_type = `FU_TYPE_ALU;
			/* AND     */  {`INSTR_TYPE_SPECIAL     , 6'b100100}: fu_type = `FU_TYPE_ALU;
			/* ANDI    */  {`INSTR_TYPE_COMMON      , 6'b001100}: fu_type = `FU_TYPE_ALU;
			/* OR      */  {`INSTR_TYPE_SPECIAL     , 6'b100101}: fu_type = `FU_TYPE_ALU;
			/* ORI     */  {`INSTR_TYPE_COMMON      , 6'b001101}: fu_type = `FU_TYPE_ALU;
			/* XOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100110}: fu_type = `FU_TYPE_ALU;
			/* XORI    */  {`INSTR_TYPE_COMMON      , 6'b001110}: fu_type = `FU_TYPE_ALU;
			/* NOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100111}: fu_type = `FU_TYPE_ALU;
			/* SLT     */  {`INSTR_TYPE_SPECIAL     , 6'b101010}: fu_type = `FU_TYPE_ALU;
			/* SLTU    */  {`INSTR_TYPE_SPECIAL     , 6'b101011}: fu_type = `FU_TYPE_ALU;
			/* SLTI    */  {`INSTR_TYPE_COMMON      , 6'b001010}: fu_type = `FU_TYPE_ALU;
			/* SLTIU   */  {`INSTR_TYPE_COMMON      , 6'b001011}: fu_type = `FU_TYPE_ALU;
			/* SLL     */  {`INSTR_TYPE_SPECIAL     , 6'b000000}: fu_type = `FU_TYPE_ALU;
			/* SLLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000100}: fu_type = `FU_TYPE_ALU;
			/* SRL     */  {`INSTR_TYPE_SPECIAL     , 6'b000010}: fu_type = `FU_TYPE_ALU;
			/* SRLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000110}: fu_type = `FU_TYPE_ALU;
			/* SRA     */  {`INSTR_TYPE_SPECIAL     , 6'b000011}: fu_type = `FU_TYPE_ALU;
			/* SRAV    */  {`INSTR_TYPE_SPECIAL     , 6'b000111}: fu_type = `FU_TYPE_ALU;
			/* LUI     */  {`INSTR_TYPE_COMMON      , 6'b001111}: fu_type = `FU_TYPE_ALU;
			/* BGEZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010001}: fu_type = `FU_TYPE_BRU;
			/* BLTZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010000}: fu_type = `FU_TYPE_BRU;
			/* BEQ     */  {`INSTR_TYPE_COMMON      , 6'b000100}: fu_type = `FU_TYPE_BRU;
			/* BGEZ    */  {`INSTR_TYPE_REGIMM      , 6'b000001}: fu_type = `FU_TYPE_BRU;
			/* BGTZ    */  {`INSTR_TYPE_COMMON      , 6'b000111}: fu_type = `FU_TYPE_BRU;
			/* BLEZ    */  {`INSTR_TYPE_COMMON      , 6'b000110}: fu_type = `FU_TYPE_BRU;
			/* BLTZ    */  {`INSTR_TYPE_REGIMM      , 6'b000000}: fu_type = `FU_TYPE_BRU;
			/* BNE     */  {`INSTR_TYPE_COMMON      , 6'b000101}: fu_type = `FU_TYPE_BRU;
			/* J       */  {`INSTR_TYPE_COMMON      , 6'b000010}: fu_type = `FU_TYPE_BRU;
			/* JAL     */  {`INSTR_TYPE_COMMON      , 6'b000011}: fu_type = `FU_TYPE_BRU;
			/* JALR    */  {`INSTR_TYPE_SPECIAL     , 6'b001001}: fu_type = `FU_TYPE_BRU;
			/* JR      */  {`INSTR_TYPE_SPECIAL     , 6'b001000}: fu_type = `FU_TYPE_BRU;
			/* MUL     */  {`INSTR_TYPE_SPECIAL2    , 6'b000010}: fu_type = `FU_TYPE_MDU;
			/* MULT    */  {`INSTR_TYPE_SPECIAL     , 6'b011000}: fu_type = `FU_TYPE_MDU;
			/* MULTU   */  {`INSTR_TYPE_SPECIAL     , 6'b011001}: fu_type = `FU_TYPE_MDU;
			/* DIV     */  {`INSTR_TYPE_SPECIAL     , 6'b011010}: fu_type = `FU_TYPE_MDU;
			/* DIVU    */  {`INSTR_TYPE_SPECIAL     , 6'b011011}: fu_type = `FU_TYPE_MDU;
			/* MFHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010000}: fu_type = `FU_TYPE_MDU;
			/* MTHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010001}: fu_type = `FU_TYPE_MDU;
			/* MFLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010010}: fu_type = `FU_TYPE_MDU;
			/* MTLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010011}: fu_type = `FU_TYPE_MDU;
			/* LB      */  {`INSTR_TYPE_COMMON      , 6'b100000}: fu_type = `FU_TYPE_LSU;
			/* LBU     */  {`INSTR_TYPE_COMMON      , 6'b100100}: fu_type = `FU_TYPE_LSU;
			/* LH      */  {`INSTR_TYPE_COMMON      , 6'b100001}: fu_type = `FU_TYPE_LSU;
			/* LHU     */  {`INSTR_TYPE_COMMON      , 6'b100101}: fu_type = `FU_TYPE_LSU;
			/* LW      */  {`INSTR_TYPE_COMMON      , 6'b100011}: fu_type = `FU_TYPE_LSU;
			/* SB      */  {`INSTR_TYPE_COMMON      , 6'b101000}: fu_type = `FU_TYPE_LSU;
			/* SH      */  {`INSTR_TYPE_COMMON      , 6'b101001}: fu_type = `FU_TYPE_LSU;
			/* SW      */  {`INSTR_TYPE_COMMON      , 6'b101011}: fu_type = `FU_TYPE_LSU;
			/* LWL     */  {`INSTR_TYPE_COMMON      , 6'b100010}: fu_type = `FU_TYPE_LSU;
			/* LWR     */  {`INSTR_TYPE_COMMON      , 6'b100110}: fu_type = `FU_TYPE_LSU;
			/* SWL     */  {`INSTR_TYPE_COMMON      , 6'b101010}: fu_type = `FU_TYPE_LSU;
			/* SWR     */  {`INSTR_TYPE_COMMON      , 6'b101110}: fu_type = `FU_TYPE_LSU;
			/* MFC0    */  {`INSTR_TYPE_COP0        , 6'b000000}: fu_type = `FU_TYPE_ALU;
			/* MTC0    */  {`INSTR_TYPE_COP0        , 6'b000100}: fu_type = `FU_TYPE_ALU;
			/* ERET    */  {`INSTR_TYPE_COP0        , 6'b010000}: fu_type = `FU_TYPE_BRU;
			/* SYSCALL */  {`INSTR_TYPE_SPECIAL     , 6'b001100}: fu_type = `FU_TYPE_BRU;
			/* BREAK   */  {`INSTR_TYPE_SPECIAL     , 6'b001101}: fu_type = `FU_TYPE_BRU;
			/* MOVN    */  {`INSTR_TYPE_SPECIAL     , 6'b001011}: fu_type = `FU_TYPE_ALU;
			/* MOVZ    */  {`INSTR_TYPE_SPECIAL     , 6'b001010}: fu_type = `FU_TYPE_ALU;
			default:      fu_type = `FU_TYPE_X;
		endcase
	end

	always @(*) begin
		case(lookup_idx)
			/* ADD     */  {`INSTR_TYPE_SPECIAL     , 6'b100000}: fu_op = `FU_OP_ALU_ADD_OV;
			/* ADDU    */  {`INSTR_TYPE_SPECIAL     , 6'b100001}: fu_op = `FU_OP_ALU_ADD;
			/* ADDI    */  {`INSTR_TYPE_COMMON      , 6'b001000}: fu_op = `FU_OP_ALU_ADD_OV;
			/* ADDIU   */  {`INSTR_TYPE_COMMON      , 6'b001001}: fu_op = `FU_OP_ALU_ADD;
			/* SUB     */  {`INSTR_TYPE_SPECIAL     , 6'b100010}: fu_op = `FU_OP_ALU_SUB_OV;
			/* SUBU    */  {`INSTR_TYPE_SPECIAL     , 6'b100011}: fu_op = `FU_OP_ALU_SUB;
			/* AND     */  {`INSTR_TYPE_SPECIAL     , 6'b100100}: fu_op = `FU_OP_ALU_AND;
			/* ANDI    */  {`INSTR_TYPE_COMMON      , 6'b001100}: fu_op = `FU_OP_ALU_AND;
			/* OR      */  {`INSTR_TYPE_SPECIAL     , 6'b100101}: fu_op = `FU_OP_ALU_OR;
			/* ORI     */  {`INSTR_TYPE_COMMON      , 6'b001101}: fu_op = `FU_OP_ALU_OR;
			/* XOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100110}: fu_op = `FU_OP_ALU_XOR;
			/* XORI    */  {`INSTR_TYPE_COMMON      , 6'b001110}: fu_op = `FU_OP_ALU_XOR;
			/* NOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100111}: fu_op = `FU_OP_ALU_NOR;
			/* SLT     */  {`INSTR_TYPE_SPECIAL     , 6'b101010}: fu_op = `FU_OP_ALU_SLT;
			/* SLTU    */  {`INSTR_TYPE_SPECIAL     , 6'b101011}: fu_op = `FU_OP_ALU_SLTU;
			/* SLTI    */  {`INSTR_TYPE_COMMON      , 6'b001010}: fu_op = `FU_OP_ALU_SLT;
			/* SLTIU   */  {`INSTR_TYPE_COMMON      , 6'b001011}: fu_op = `FU_OP_ALU_SLTU;
			/* SLL     */  {`INSTR_TYPE_SPECIAL     , 6'b000000}: fu_op = `FU_OP_ALU_SLL;
			/* SLLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000100}: fu_op = `FU_OP_ALU_SLL;
			/* SRL     */  {`INSTR_TYPE_SPECIAL     , 6'b000010}: fu_op = `FU_OP_ALU_SRL;
			/* SRLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000110}: fu_op = `FU_OP_ALU_SRL;
			/* SRA     */  {`INSTR_TYPE_SPECIAL     , 6'b000011}: fu_op = `FU_OP_ALU_SRA;
			/* SRAV    */  {`INSTR_TYPE_SPECIAL     , 6'b000111}: fu_op = `FU_OP_ALU_SRA;
			/* LUI     */  {`INSTR_TYPE_COMMON      , 6'b001111}: fu_op = `FU_OP_ALU_LUI;
			/* BGEZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010001}: fu_op = `FU_OP_BRU_BGEZAL;
			/* BLTZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010000}: fu_op = `FU_OP_BRU_BLTZAL;
			/* BEQ     */  {`INSTR_TYPE_COMMON      , 6'b000100}: fu_op = `FU_OP_BRU_BEQ;
			/* BGEZ    */  {`INSTR_TYPE_REGIMM      , 6'b000001}: fu_op = `FU_OP_BRU_BGEZ;
			/* BGTZ    */  {`INSTR_TYPE_COMMON      , 6'b000111}: fu_op = `FU_OP_BRU_BGTZ;
			/* BLEZ    */  {`INSTR_TYPE_COMMON      , 6'b000110}: fu_op = `FU_OP_BRU_BLEZ;
			/* BLTZ    */  {`INSTR_TYPE_REGIMM      , 6'b000000}: fu_op = `FU_OP_BRU_BLTZ;
			/* BNE     */  {`INSTR_TYPE_COMMON      , 6'b000101}: fu_op = `FU_OP_BRU_BNE;
			/* J       */  {`INSTR_TYPE_COMMON      , 6'b000010}: fu_op = `FU_OP_BRU_J;
			/* JAL     */  {`INSTR_TYPE_COMMON      , 6'b000011}: fu_op = `FU_OP_BRU_JAL;
			/* JALR    */  {`INSTR_TYPE_SPECIAL     , 6'b001001}: fu_op = `FU_OP_BRU_JALR;
			/* JR      */  {`INSTR_TYPE_SPECIAL     , 6'b001000}: fu_op = `FU_OP_BRU_JR;
			/* MUL     */  {`INSTR_TYPE_SPECIAL2    , 6'b000010}: fu_op = `FU_OP_MDU_MUL;
			/* MULT    */  {`INSTR_TYPE_SPECIAL     , 6'b011000}: fu_op = `FU_OP_MDU_MULT;
			/* MULTU   */  {`INSTR_TYPE_SPECIAL     , 6'b011001}: fu_op = `FU_OP_MDU_MULTU;
			/* DIV     */  {`INSTR_TYPE_SPECIAL     , 6'b011010}: fu_op = `FU_OP_MDU_DIV;
			/* DIVU    */  {`INSTR_TYPE_SPECIAL     , 6'b011011}: fu_op = `FU_OP_MDU_DIVU;
			/* MFHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010000}: fu_op = `FU_OP_MDU_MFHI;
			/* MTHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010001}: fu_op = `FU_OP_MDU_MTHI;
			/* MFLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010010}: fu_op = `FU_OP_MDU_MFLO;
			/* MTLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010011}: fu_op = `FU_OP_MDU_MTLO;
			/* LB      */  {`INSTR_TYPE_COMMON      , 6'b100000}: fu_op = `FU_OP_LSU_LB;
			/* LBU     */  {`INSTR_TYPE_COMMON      , 6'b100100}: fu_op = `FU_OP_LSU_LBU;
			/* LH      */  {`INSTR_TYPE_COMMON      , 6'b100001}: fu_op = `FU_OP_LSU_LH;
			/* LHU     */  {`INSTR_TYPE_COMMON      , 6'b100101}: fu_op = `FU_OP_LSU_LHU;
			/* LW      */  {`INSTR_TYPE_COMMON      , 6'b100011}: fu_op = `FU_OP_LSU_LW;
			/* SB      */  {`INSTR_TYPE_COMMON      , 6'b101000}: fu_op = `FU_OP_LSU_SB;
			/* SH      */  {`INSTR_TYPE_COMMON      , 6'b101001}: fu_op = `FU_OP_LSU_SH;
			/* SW      */  {`INSTR_TYPE_COMMON      , 6'b101011}: fu_op = `FU_OP_LSU_SW;
			/* LWL     */  {`INSTR_TYPE_COMMON      , 6'b100010}: fu_op = `FU_OP_LSU_LWL;
			/* LWR     */  {`INSTR_TYPE_COMMON      , 6'b100110}: fu_op = `FU_OP_LSU_LWR;
			/* SWL     */  {`INSTR_TYPE_COMMON      , 6'b101010}: fu_op = `FU_OP_LSU_SWL;
			/* SWR     */  {`INSTR_TYPE_COMMON      , 6'b101110}: fu_op = `FU_OP_LSU_SWR;
			/* MFC0    */  {`INSTR_TYPE_COP0        , 6'b000000}: fu_op = `FU_OP_ALU_MFC0;
			/* MTC0    */  {`INSTR_TYPE_COP0        , 6'b000100}: fu_op = `FU_OP_ALU_MTC0;
			/* ERET    */  {`INSTR_TYPE_COP0        , 6'b010000}: fu_op = `FU_OP_BRU_ERET;
			/* MOVN    */  {`INSTR_TYPE_SPECIAL     , 6'b001011}: fu_op = `FU_OP_ALU_MOVN;
			/* MOVZ    */  {`INSTR_TYPE_SPECIAL     , 6'b001010}: fu_op = `FU_OP_ALU_MOVZ;
			default:      fu_op = `FU_OP_X;
		endcase
	end

	always @(*) begin
		case(lookup_idx)
			/* ADD     */  {`INSTR_TYPE_SPECIAL     , 6'b100000}: b_src = `B_SRC_REG;
			/* ADDU    */  {`INSTR_TYPE_SPECIAL     , 6'b100001}: b_src = `B_SRC_REG;
			/* ADDI    */  {`INSTR_TYPE_COMMON      , 6'b001000}: b_src = `B_SRC_IMM;
			/* ADDIU   */  {`INSTR_TYPE_COMMON      , 6'b001001}: b_src = `B_SRC_IMM;
			/* SUB     */  {`INSTR_TYPE_SPECIAL     , 6'b100010}: b_src = `B_SRC_REG;
			/* SUBU    */  {`INSTR_TYPE_SPECIAL     , 6'b100011}: b_src = `B_SRC_REG;
			/* AND     */  {`INSTR_TYPE_SPECIAL     , 6'b100100}: b_src = `B_SRC_REG;
			/* ANDI    */  {`INSTR_TYPE_COMMON      , 6'b001100}: b_src = `B_SRC_IMM;
			/* OR      */  {`INSTR_TYPE_SPECIAL     , 6'b100101}: b_src = `B_SRC_REG;
			/* ORI     */  {`INSTR_TYPE_COMMON      , 6'b001101}: b_src = `B_SRC_IMM;
			/* XOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100110}: b_src = `B_SRC_REG;
			/* XORI    */  {`INSTR_TYPE_COMMON      , 6'b001110}: b_src = `B_SRC_IMM;
			/* NOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100111}: b_src = `B_SRC_REG;
			/* SLT     */  {`INSTR_TYPE_SPECIAL     , 6'b101010}: b_src = `B_SRC_REG;
			/* SLTU    */  {`INSTR_TYPE_SPECIAL     , 6'b101011}: b_src = `B_SRC_REG;
			/* SLTI    */  {`INSTR_TYPE_COMMON      , 6'b001010}: b_src = `B_SRC_IMM;
			/* SLTIU   */  {`INSTR_TYPE_COMMON      , 6'b001011}: b_src = `B_SRC_IMM;
			/* SLL     */  {`INSTR_TYPE_SPECIAL     , 6'b000000}: b_src = `B_SRC_REG;
			/* SLLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000100}: b_src = `B_SRC_REG;
			/* SRL     */  {`INSTR_TYPE_SPECIAL     , 6'b000010}: b_src = `B_SRC_REG;
			/* SRLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000110}: b_src = `B_SRC_REG;
			/* SRA     */  {`INSTR_TYPE_SPECIAL     , 6'b000011}: b_src = `B_SRC_REG;
			/* SRAV    */  {`INSTR_TYPE_SPECIAL     , 6'b000111}: b_src = `B_SRC_REG;
			/* LUI     */  {`INSTR_TYPE_COMMON      , 6'b001111}: b_src = `B_SRC_IMM;
			/* BEQ     */  {`INSTR_TYPE_COMMON      , 6'b000100}: b_src = `B_SRC_REG;
			/* BNE     */  {`INSTR_TYPE_COMMON      , 6'b000101}: b_src = `B_SRC_REG;
			/* MUL     */  {`INSTR_TYPE_SPECIAL2    , 6'b000010}: b_src = `B_SRC_REG;
			/* MULT    */  {`INSTR_TYPE_SPECIAL     , 6'b011000}: b_src = `B_SRC_REG;
			/* MULTU   */  {`INSTR_TYPE_SPECIAL     , 6'b011001}: b_src = `B_SRC_REG;
			/* DIV     */  {`INSTR_TYPE_SPECIAL     , 6'b011010}: b_src = `B_SRC_REG;
			/* DIVU    */  {`INSTR_TYPE_SPECIAL     , 6'b011011}: b_src = `B_SRC_REG;
			/* SB      */  {`INSTR_TYPE_COMMON      , 6'b101000}: b_src = `B_SRC_REG;
			/* SH      */  {`INSTR_TYPE_COMMON      , 6'b101001}: b_src = `B_SRC_REG;
			/* SW      */  {`INSTR_TYPE_COMMON      , 6'b101011}: b_src = `B_SRC_REG;
			/* SWL     */  {`INSTR_TYPE_COMMON      , 6'b101010}: b_src = `B_SRC_REG;
			/* SWR     */  {`INSTR_TYPE_COMMON      , 6'b101110}: b_src = `B_SRC_REG;
			/* MTC0    */  {`INSTR_TYPE_COP0        , 6'b000100}: b_src = `B_SRC_REG;
			/* MOVN    */  {`INSTR_TYPE_SPECIAL     , 6'b001011}: b_src = `B_SRC_REG;
			/* MOVZ    */  {`INSTR_TYPE_SPECIAL     , 6'b001010}: b_src = `B_SRC_REG;
			default:      b_src = `B_SRC_X;
		endcase
	end

	always @(*) begin
		case(lookup_idx)
			/* ADDI    */  {`INSTR_TYPE_COMMON      , 6'b001000}: ext_type = `EXT_TYPE_SIGN;
			/* ADDIU   */  {`INSTR_TYPE_COMMON      , 6'b001001}: ext_type = `EXT_TYPE_SIGN;
			/* ANDI    */  {`INSTR_TYPE_COMMON      , 6'b001100}: ext_type = `EXT_TYPE_ZERO;
			/* ORI     */  {`INSTR_TYPE_COMMON      , 6'b001101}: ext_type = `EXT_TYPE_ZERO;
			/* XORI    */  {`INSTR_TYPE_COMMON      , 6'b001110}: ext_type = `EXT_TYPE_ZERO;
			/* SLTI    */  {`INSTR_TYPE_COMMON      , 6'b001010}: ext_type = `EXT_TYPE_SIGN;
			/* SLTIU   */  {`INSTR_TYPE_COMMON      , 6'b001011}: ext_type = `EXT_TYPE_SIGN;
			/* LB      */  {`INSTR_TYPE_COMMON      , 6'b100000}: ext_type = `EXT_TYPE_SIGN;
			/* LBU     */  {`INSTR_TYPE_COMMON      , 6'b100100}: ext_type = `EXT_TYPE_SIGN;
			/* LH      */  {`INSTR_TYPE_COMMON      , 6'b100001}: ext_type = `EXT_TYPE_SIGN;
			/* LHU     */  {`INSTR_TYPE_COMMON      , 6'b100101}: ext_type = `EXT_TYPE_SIGN;
			/* LW      */  {`INSTR_TYPE_COMMON      , 6'b100011}: ext_type = `EXT_TYPE_SIGN;
			/* SB      */  {`INSTR_TYPE_COMMON      , 6'b101000}: ext_type = `EXT_TYPE_SIGN;
			/* SH      */  {`INSTR_TYPE_COMMON      , 6'b101001}: ext_type = `EXT_TYPE_SIGN;
			/* SW      */  {`INSTR_TYPE_COMMON      , 6'b101011}: ext_type = `EXT_TYPE_SIGN;
			/* LWL     */  {`INSTR_TYPE_COMMON      , 6'b100010}: ext_type = `EXT_TYPE_SIGN;
			/* LWR     */  {`INSTR_TYPE_COMMON      , 6'b100110}: ext_type = `EXT_TYPE_SIGN;
			/* SWL     */  {`INSTR_TYPE_COMMON      , 6'b101010}: ext_type = `EXT_TYPE_SIGN;
			/* SWR     */  {`INSTR_TYPE_COMMON      , 6'b101110}: ext_type = `EXT_TYPE_SIGN;
			default:      ext_type = `EXT_TYPE_X;
		endcase
	end

	always @(*) begin
		case(lookup_idx)
			/* ADD     */  {`INSTR_TYPE_SPECIAL     , 6'b100000}: rd_sel = `RD_SEL_RD;
			/* ADDU    */  {`INSTR_TYPE_SPECIAL     , 6'b100001}: rd_sel = `RD_SEL_RD;
			/* ADDI    */  {`INSTR_TYPE_COMMON      , 6'b001000}: rd_sel = `RD_SEL_RT;
			/* ADDIU   */  {`INSTR_TYPE_COMMON      , 6'b001001}: rd_sel = `RD_SEL_RT;
			/* SUB     */  {`INSTR_TYPE_SPECIAL     , 6'b100010}: rd_sel = `RD_SEL_RD;
			/* SUBU    */  {`INSTR_TYPE_SPECIAL     , 6'b100011}: rd_sel = `RD_SEL_RD;
			/* AND     */  {`INSTR_TYPE_SPECIAL     , 6'b100100}: rd_sel = `RD_SEL_RD;
			/* ANDI    */  {`INSTR_TYPE_COMMON      , 6'b001100}: rd_sel = `RD_SEL_RT;
			/* OR      */  {`INSTR_TYPE_SPECIAL     , 6'b100101}: rd_sel = `RD_SEL_RD;
			/* ORI     */  {`INSTR_TYPE_COMMON      , 6'b001101}: rd_sel = `RD_SEL_RT;
			/* XOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100110}: rd_sel = `RD_SEL_RD;
			/* XORI    */  {`INSTR_TYPE_COMMON      , 6'b001110}: rd_sel = `RD_SEL_RT;
			/* NOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100111}: rd_sel = `RD_SEL_RD;
			/* SLT     */  {`INSTR_TYPE_SPECIAL     , 6'b101010}: rd_sel = `RD_SEL_RD;
			/* SLTU    */  {`INSTR_TYPE_SPECIAL     , 6'b101011}: rd_sel = `RD_SEL_RD;
			/* SLTI    */  {`INSTR_TYPE_COMMON      , 6'b001010}: rd_sel = `RD_SEL_RT;
			/* SLTIU   */  {`INSTR_TYPE_COMMON      , 6'b001011}: rd_sel = `RD_SEL_RT;
			/* SLL     */  {`INSTR_TYPE_SPECIAL     , 6'b000000}: rd_sel = `RD_SEL_RD;
			/* SLLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000100}: rd_sel = `RD_SEL_RD;
			/* SRL     */  {`INSTR_TYPE_SPECIAL     , 6'b000010}: rd_sel = `RD_SEL_RD;
			/* SRLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000110}: rd_sel = `RD_SEL_RD;
			/* SRA     */  {`INSTR_TYPE_SPECIAL     , 6'b000011}: rd_sel = `RD_SEL_RD;
			/* SRAV    */  {`INSTR_TYPE_SPECIAL     , 6'b000111}: rd_sel = `RD_SEL_RD;
			/* LUI     */  {`INSTR_TYPE_COMMON      , 6'b001111}: rd_sel = `RD_SEL_RT;
			/* BGEZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010001}: rd_sel = `RD_SEL_31;
			/* BLTZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010000}: rd_sel = `RD_SEL_31;
			/* JAL     */  {`INSTR_TYPE_COMMON      , 6'b000011}: rd_sel = `RD_SEL_31;
			/* JALR    */  {`INSTR_TYPE_SPECIAL     , 6'b001001}: rd_sel = `RD_SEL_RD;
			/* MUL     */  {`INSTR_TYPE_SPECIAL2    , 6'b000010}: rd_sel = `RD_SEL_RD;
			/* MULT    */  {`INSTR_TYPE_SPECIAL     , 6'b011000}: rd_sel = `RD_SEL_HILO;
			/* MULTU   */  {`INSTR_TYPE_SPECIAL     , 6'b011001}: rd_sel = `RD_SEL_HILO;
			/* DIV     */  {`INSTR_TYPE_SPECIAL     , 6'b011010}: rd_sel = `RD_SEL_HILO;
			/* DIVU    */  {`INSTR_TYPE_SPECIAL     , 6'b011011}: rd_sel = `RD_SEL_HILO;
			/* MFHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010000}: rd_sel = `RD_SEL_RD;
			/* MTHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010001}: rd_sel = `RD_SEL_HI;
			/* MFLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010010}: rd_sel = `RD_SEL_RD;
			/* MTLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010011}: rd_sel = `RD_SEL_LO;
			/* LB      */  {`INSTR_TYPE_COMMON      , 6'b100000}: rd_sel = `RD_SEL_RT;
			/* LBU     */  {`INSTR_TYPE_COMMON      , 6'b100100}: rd_sel = `RD_SEL_RT;
			/* LH      */  {`INSTR_TYPE_COMMON      , 6'b100001}: rd_sel = `RD_SEL_RT;
			/* LHU     */  {`INSTR_TYPE_COMMON      , 6'b100101}: rd_sel = `RD_SEL_RT;
			/* LW      */  {`INSTR_TYPE_COMMON      , 6'b100011}: rd_sel = `RD_SEL_RT;
			/* LWL     */  {`INSTR_TYPE_COMMON      , 6'b100010}: rd_sel = `RD_SEL_RT;
			/* LWR     */  {`INSTR_TYPE_COMMON      , 6'b100110}: rd_sel = `RD_SEL_RT;
			/* MFC0    */  {`INSTR_TYPE_COP0        , 6'b000000}: rd_sel = `RD_SEL_RT;
			/* MTC0    */  {`INSTR_TYPE_COP0        , 6'b000100}: rd_sel = `RD_SEL_RD;
			/* MOVN    */  {`INSTR_TYPE_SPECIAL     , 6'b001011}: rd_sel = `RD_SEL_RD;
			/* MOVZ    */  {`INSTR_TYPE_SPECIAL     , 6'b001010}: rd_sel = `RD_SEL_RD;
			default:      rd_sel = `RD_SEL_X;
		endcase
	end

	always @(*) begin
		case(lookup_idx)
			/* ADD     */  {`INSTR_TYPE_SPECIAL     , 6'b100000}: a_src = `A_SRC_RS;
			/* ADDU    */  {`INSTR_TYPE_SPECIAL     , 6'b100001}: a_src = `A_SRC_RS;
			/* ADDI    */  {`INSTR_TYPE_COMMON      , 6'b001000}: a_src = `A_SRC_RS;
			/* ADDIU   */  {`INSTR_TYPE_COMMON      , 6'b001001}: a_src = `A_SRC_RS;
			/* SUB     */  {`INSTR_TYPE_SPECIAL     , 6'b100010}: a_src = `A_SRC_RS;
			/* SUBU    */  {`INSTR_TYPE_SPECIAL     , 6'b100011}: a_src = `A_SRC_RS;
			/* AND     */  {`INSTR_TYPE_SPECIAL     , 6'b100100}: a_src = `A_SRC_RS;
			/* ANDI    */  {`INSTR_TYPE_COMMON      , 6'b001100}: a_src = `A_SRC_RS;
			/* OR      */  {`INSTR_TYPE_SPECIAL     , 6'b100101}: a_src = `A_SRC_RS;
			/* ORI     */  {`INSTR_TYPE_COMMON      , 6'b001101}: a_src = `A_SRC_RS;
			/* XOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100110}: a_src = `A_SRC_RS;
			/* XORI    */  {`INSTR_TYPE_COMMON      , 6'b001110}: a_src = `A_SRC_RS;
			/* NOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100111}: a_src = `A_SRC_RS;
			/* SLT     */  {`INSTR_TYPE_SPECIAL     , 6'b101010}: a_src = `A_SRC_RS;
			/* SLTU    */  {`INSTR_TYPE_SPECIAL     , 6'b101011}: a_src = `A_SRC_RS;
			/* SLTI    */  {`INSTR_TYPE_COMMON      , 6'b001010}: a_src = `A_SRC_RS;
			/* SLTIU   */  {`INSTR_TYPE_COMMON      , 6'b001011}: a_src = `A_SRC_RS;
			/* SLL     */  {`INSTR_TYPE_SPECIAL     , 6'b000000}: a_src = `A_SRC_SA;
			/* SLLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000100}: a_src = `A_SRC_RS;
			/* SRL     */  {`INSTR_TYPE_SPECIAL     , 6'b000010}: a_src = `A_SRC_SA;
			/* SRLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000110}: a_src = `A_SRC_RS;
			/* SRA     */  {`INSTR_TYPE_SPECIAL     , 6'b000011}: a_src = `A_SRC_SA;
			/* SRAV    */  {`INSTR_TYPE_SPECIAL     , 6'b000111}: a_src = `A_SRC_RS;
			/* BGEZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010001}: a_src = `A_SRC_RS;
			/* BLTZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010000}: a_src = `A_SRC_RS;
			/* BEQ     */  {`INSTR_TYPE_COMMON      , 6'b000100}: a_src = `A_SRC_RS;
			/* BGEZ    */  {`INSTR_TYPE_REGIMM      , 6'b000001}: a_src = `A_SRC_RS;
			/* BGTZ    */  {`INSTR_TYPE_COMMON      , 6'b000111}: a_src = `A_SRC_RS;
			/* BLEZ    */  {`INSTR_TYPE_COMMON      , 6'b000110}: a_src = `A_SRC_RS;
			/* BLTZ    */  {`INSTR_TYPE_REGIMM      , 6'b000000}: a_src = `A_SRC_RS;
			/* BNE     */  {`INSTR_TYPE_COMMON      , 6'b000101}: a_src = `A_SRC_RS;
			/* JALR    */  {`INSTR_TYPE_SPECIAL     , 6'b001001}: a_src = `A_SRC_RS;
			/* JR      */  {`INSTR_TYPE_SPECIAL     , 6'b001000}: a_src = `A_SRC_RS;
			/* MUL     */  {`INSTR_TYPE_SPECIAL2    , 6'b000010}: a_src = `A_SRC_RS;
			/* MULT    */  {`INSTR_TYPE_SPECIAL     , 6'b011000}: a_src = `A_SRC_RS;
			/* MULTU   */  {`INSTR_TYPE_SPECIAL     , 6'b011001}: a_src = `A_SRC_RS;
			/* DIV     */  {`INSTR_TYPE_SPECIAL     , 6'b011010}: a_src = `A_SRC_RS;
			/* DIVU    */  {`INSTR_TYPE_SPECIAL     , 6'b011011}: a_src = `A_SRC_RS;
			/* MFHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010000}: a_src = `A_SRC_HI;
			/* MTHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010001}: a_src = `A_SRC_RS;
			/* MFLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010010}: a_src = `A_SRC_LO;
			/* MTLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010011}: a_src = `A_SRC_RS;
			/* LB      */  {`INSTR_TYPE_COMMON      , 6'b100000}: a_src = `A_SRC_RS;
			/* LBU     */  {`INSTR_TYPE_COMMON      , 6'b100100}: a_src = `A_SRC_RS;
			/* LH      */  {`INSTR_TYPE_COMMON      , 6'b100001}: a_src = `A_SRC_RS;
			/* LHU     */  {`INSTR_TYPE_COMMON      , 6'b100101}: a_src = `A_SRC_RS;
			/* LW      */  {`INSTR_TYPE_COMMON      , 6'b100011}: a_src = `A_SRC_RS;
			/* SB      */  {`INSTR_TYPE_COMMON      , 6'b101000}: a_src = `A_SRC_RS;
			/* SH      */  {`INSTR_TYPE_COMMON      , 6'b101001}: a_src = `A_SRC_RS;
			/* SW      */  {`INSTR_TYPE_COMMON      , 6'b101011}: a_src = `A_SRC_RS;
			/* LWL     */  {`INSTR_TYPE_COMMON      , 6'b100010}: a_src = `A_SRC_RS;
			/* LWR     */  {`INSTR_TYPE_COMMON      , 6'b100110}: a_src = `A_SRC_RS;
			/* SWL     */  {`INSTR_TYPE_COMMON      , 6'b101010}: a_src = `A_SRC_RS;
			/* SWR     */  {`INSTR_TYPE_COMMON      , 6'b101110}: a_src = `A_SRC_RS;
			/* MFC0    */  {`INSTR_TYPE_COP0        , 6'b000000}: a_src = `A_SRC_CP0;
			/* ERET    */  {`INSTR_TYPE_COP0        , 6'b010000}: a_src = `A_SRC_CP0_EPC;
			/* MOVN    */  {`INSTR_TYPE_SPECIAL     , 6'b001011}: a_src = `A_SRC_RS;
			/* MOVZ    */  {`INSTR_TYPE_SPECIAL     , 6'b001010}: a_src = `A_SRC_RS;
			default:      a_src = `A_SRC_X;
		endcase
	end

	always @(*) begin
		case(lookup_idx)
			/* ERET    */  {`INSTR_TYPE_COP0        , 6'b010000}: de_special = `DE_SPECIAL_ERET;
			/* SYSCALL */  {`INSTR_TYPE_SPECIAL     , 6'b001100}: de_special = `DE_SPECIAL_SYSCALL;
			/* BREAK   */  {`INSTR_TYPE_SPECIAL     , 6'b001101}: de_special = `DE_SPECIAL_BREAK;
			default:      de_special = `DE_SPECIAL_X;
		endcase
	end

	always @(*) begin
		case(lookup_idx)
			/* ADD     */  {`INSTR_TYPE_SPECIAL     , 6'b100000}: mask = 26'b00000000000000011111111111;
			/* ADDU    */  {`INSTR_TYPE_SPECIAL     , 6'b100001}: mask = 26'b00000000000000011111111111;
			/* ADDI    */  {`INSTR_TYPE_COMMON      , 6'b001000}: mask = 26'b00000000000000000000000000;
			/* ADDIU   */  {`INSTR_TYPE_COMMON      , 6'b001001}: mask = 26'b00000000000000000000000000;
			/* SUB     */  {`INSTR_TYPE_SPECIAL     , 6'b100010}: mask = 26'b00000000000000011111111111;
			/* SUBU    */  {`INSTR_TYPE_SPECIAL     , 6'b100011}: mask = 26'b00000000000000011111111111;
			/* AND     */  {`INSTR_TYPE_SPECIAL     , 6'b100100}: mask = 26'b00000000000000011111111111;
			/* ANDI    */  {`INSTR_TYPE_COMMON      , 6'b001100}: mask = 26'b00000000000000000000000000;
			/* OR      */  {`INSTR_TYPE_SPECIAL     , 6'b100101}: mask = 26'b00000000000000011111111111;
			/* ORI     */  {`INSTR_TYPE_COMMON      , 6'b001101}: mask = 26'b00000000000000000000000000;
			/* XOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100110}: mask = 26'b00000000000000011111111111;
			/* XORI    */  {`INSTR_TYPE_COMMON      , 6'b001110}: mask = 26'b00000000000000000000000000;
			/* NOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100111}: mask = 26'b00000000000000011111111111;
			/* SLT     */  {`INSTR_TYPE_SPECIAL     , 6'b101010}: mask = 26'b00000000000000011111111111;
			/* SLTU    */  {`INSTR_TYPE_SPECIAL     , 6'b101011}: mask = 26'b00000000000000011111111111;
			/* SLTI    */  {`INSTR_TYPE_COMMON      , 6'b001010}: mask = 26'b00000000000000000000000000;
			/* SLTIU   */  {`INSTR_TYPE_COMMON      , 6'b001011}: mask = 26'b00000000000000000000000000;
			/* SLL     */  {`INSTR_TYPE_SPECIAL     , 6'b000000}: mask = 26'b11111000000000000000111111;
			/* SLLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000100}: mask = 26'b00000000000000011111111111;
			/* SRL     */  {`INSTR_TYPE_SPECIAL     , 6'b000010}: mask = 26'b11111000000000000000111111;
			/* SRLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000110}: mask = 26'b00000000000000011111111111;
			/* SRA     */  {`INSTR_TYPE_SPECIAL     , 6'b000011}: mask = 26'b11111000000000000000111111;
			/* SRAV    */  {`INSTR_TYPE_SPECIAL     , 6'b000111}: mask = 26'b00000000000000011111111111;
			/* LUI     */  {`INSTR_TYPE_COMMON      , 6'b001111}: mask = 26'b11111000000000000000000000;
			/* BGEZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010001}: mask = 26'b00000111110000000000000000;
			/* BLTZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010000}: mask = 26'b00000111110000000000000000;
			/* BEQ     */  {`INSTR_TYPE_COMMON      , 6'b000100}: mask = 26'b00000000000000000000000000;
			/* BGEZ    */  {`INSTR_TYPE_REGIMM      , 6'b000001}: mask = 26'b00000111110000000000000000;
			/* BGTZ    */  {`INSTR_TYPE_COMMON      , 6'b000111}: mask = 26'b00000111110000000000000000;
			/* BLEZ    */  {`INSTR_TYPE_COMMON      , 6'b000110}: mask = 26'b00000111110000000000000000;
			/* BLTZ    */  {`INSTR_TYPE_REGIMM      , 6'b000000}: mask = 26'b00000111110000000000000000;
			/* BNE     */  {`INSTR_TYPE_COMMON      , 6'b000101}: mask = 26'b00000000000000000000000000;
			/* J       */  {`INSTR_TYPE_COMMON      , 6'b000010}: mask = 26'b00000000000000000000000000;
			/* JAL     */  {`INSTR_TYPE_COMMON      , 6'b000011}: mask = 26'b00000000000000000000000000;
			/* JALR    */  {`INSTR_TYPE_SPECIAL     , 6'b001001}: mask = 26'b00000111110000011111111111;
			/* JR      */  {`INSTR_TYPE_SPECIAL     , 6'b001000}: mask = 26'b00000111111111111111111111;
			/* MUL     */  {`INSTR_TYPE_SPECIAL2    , 6'b000010}: mask = 26'b00000000000000011111111111;
			/* MULT    */  {`INSTR_TYPE_SPECIAL     , 6'b011000}: mask = 26'b00000000001111111111111111;
			/* MULTU   */  {`INSTR_TYPE_SPECIAL     , 6'b011001}: mask = 26'b00000000001111111111111111;
			/* DIV     */  {`INSTR_TYPE_SPECIAL     , 6'b011010}: mask = 26'b00000000001111111111111111;
			/* DIVU    */  {`INSTR_TYPE_SPECIAL     , 6'b011011}: mask = 26'b00000000001111111111111111;
			/* MFHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010000}: mask = 26'b11111111110000011111111111;
			/* MTHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010001}: mask = 26'b00000111111111111111111111;
			/* MFLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010010}: mask = 26'b11111111110000011111111111;
			/* MTLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010011}: mask = 26'b00000111111111111111111111;
			/* LB      */  {`INSTR_TYPE_COMMON      , 6'b100000}: mask = 26'b00000000000000000000000000;
			/* LBU     */  {`INSTR_TYPE_COMMON      , 6'b100100}: mask = 26'b00000000000000000000000000;
			/* LH      */  {`INSTR_TYPE_COMMON      , 6'b100001}: mask = 26'b00000000000000000000000000;
			/* LHU     */  {`INSTR_TYPE_COMMON      , 6'b100101}: mask = 26'b00000000000000000000000000;
			/* LW      */  {`INSTR_TYPE_COMMON      , 6'b100011}: mask = 26'b00000000000000000000000000;
			/* SB      */  {`INSTR_TYPE_COMMON      , 6'b101000}: mask = 26'b00000000000000000000000000;
			/* SH      */  {`INSTR_TYPE_COMMON      , 6'b101001}: mask = 26'b00000000000000000000000000;
			/* SW      */  {`INSTR_TYPE_COMMON      , 6'b101011}: mask = 26'b00000000000000000000000000;
			/* LWL     */  {`INSTR_TYPE_COMMON      , 6'b100010}: mask = 26'b00000000000000000000000000;
			/* LWR     */  {`INSTR_TYPE_COMMON      , 6'b100110}: mask = 26'b00000000000000000000000000;
			/* SWL     */  {`INSTR_TYPE_COMMON      , 6'b101010}: mask = 26'b00000000000000000000000000;
			/* SWR     */  {`INSTR_TYPE_COMMON      , 6'b101110}: mask = 26'b00000000000000000000000000;
			/* MFC0    */  {`INSTR_TYPE_COP0        , 6'b000000}: mask = 26'b11111000000000011111111000;
			/* MTC0    */  {`INSTR_TYPE_COP0        , 6'b000100}: mask = 26'b11111000000000011111111000;
			/* ERET    */  {`INSTR_TYPE_COP0        , 6'b010000}: mask = 26'b11111111111111111111111111;
			/* SYSCALL */  {`INSTR_TYPE_SPECIAL     , 6'b001100}: mask = 26'b00000000000000000000111111;
			/* BREAK   */  {`INSTR_TYPE_SPECIAL     , 6'b001101}: mask = 26'b00000000000000000000111111;
			/* MOVN    */  {`INSTR_TYPE_SPECIAL     , 6'b001011}: mask = 26'b00000000000000011111111111;
			/* MOVZ    */  {`INSTR_TYPE_SPECIAL     , 6'b001010}: mask = 26'b00000000000000011111111111;
			default:      mask = 26'b00000000000000000000000000;
		endcase
	end

	always @(*) begin
		case(lookup_idx)
			/* ADD     */  {`INSTR_TYPE_SPECIAL     , 6'b100000}: value = 26'b00000000000000000000100000;
			/* ADDU    */  {`INSTR_TYPE_SPECIAL     , 6'b100001}: value = 26'b00000000000000000000100001;
			/* ADDI    */  {`INSTR_TYPE_COMMON      , 6'b001000}: value = 26'b00000000000000000000000000;
			/* ADDIU   */  {`INSTR_TYPE_COMMON      , 6'b001001}: value = 26'b00000000000000000000000000;
			/* SUB     */  {`INSTR_TYPE_SPECIAL     , 6'b100010}: value = 26'b00000000000000000000100010;
			/* SUBU    */  {`INSTR_TYPE_SPECIAL     , 6'b100011}: value = 26'b00000000000000000000100011;
			/* AND     */  {`INSTR_TYPE_SPECIAL     , 6'b100100}: value = 26'b00000000000000000000100100;
			/* ANDI    */  {`INSTR_TYPE_COMMON      , 6'b001100}: value = 26'b00000000000000000000000000;
			/* OR      */  {`INSTR_TYPE_SPECIAL     , 6'b100101}: value = 26'b00000000000000000000100101;
			/* ORI     */  {`INSTR_TYPE_COMMON      , 6'b001101}: value = 26'b00000000000000000000000000;
			/* XOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100110}: value = 26'b00000000000000000000100110;
			/* XORI    */  {`INSTR_TYPE_COMMON      , 6'b001110}: value = 26'b00000000000000000000000000;
			/* NOR     */  {`INSTR_TYPE_SPECIAL     , 6'b100111}: value = 26'b00000000000000000000100111;
			/* SLT     */  {`INSTR_TYPE_SPECIAL     , 6'b101010}: value = 26'b00000000000000000000101010;
			/* SLTU    */  {`INSTR_TYPE_SPECIAL     , 6'b101011}: value = 26'b00000000000000000000101011;
			/* SLTI    */  {`INSTR_TYPE_COMMON      , 6'b001010}: value = 26'b00000000000000000000000000;
			/* SLTIU   */  {`INSTR_TYPE_COMMON      , 6'b001011}: value = 26'b00000000000000000000000000;
			/* SLL     */  {`INSTR_TYPE_SPECIAL     , 6'b000000}: value = 26'b00000000000000000000000000;
			/* SLLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000100}: value = 26'b00000000000000000000000100;
			/* SRL     */  {`INSTR_TYPE_SPECIAL     , 6'b000010}: value = 26'b00000000000000000000000010;
			/* SRLV    */  {`INSTR_TYPE_SPECIAL     , 6'b000110}: value = 26'b00000000000000000000000110;
			/* SRA     */  {`INSTR_TYPE_SPECIAL     , 6'b000011}: value = 26'b00000000000000000000000011;
			/* SRAV    */  {`INSTR_TYPE_SPECIAL     , 6'b000111}: value = 26'b00000000000000000000000111;
			/* LUI     */  {`INSTR_TYPE_COMMON      , 6'b001111}: value = 26'b00000000000000000000000000;
			/* BGEZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010001}: value = 26'b00000100010000000000000000;
			/* BLTZAL  */  {`INSTR_TYPE_REGIMM      , 6'b010000}: value = 26'b00000100000000000000000000;
			/* BEQ     */  {`INSTR_TYPE_COMMON      , 6'b000100}: value = 26'b00000000000000000000000000;
			/* BGEZ    */  {`INSTR_TYPE_REGIMM      , 6'b000001}: value = 26'b00000000010000000000000000;
			/* BGTZ    */  {`INSTR_TYPE_COMMON      , 6'b000111}: value = 26'b00000000000000000000000000;
			/* BLEZ    */  {`INSTR_TYPE_COMMON      , 6'b000110}: value = 26'b00000000000000000000000000;
			/* BLTZ    */  {`INSTR_TYPE_REGIMM      , 6'b000000}: value = 26'b00000000000000000000000000;
			/* BNE     */  {`INSTR_TYPE_COMMON      , 6'b000101}: value = 26'b00000000000000000000000000;
			/* J       */  {`INSTR_TYPE_COMMON      , 6'b000010}: value = 26'b00000000000000000000000000;
			/* JAL     */  {`INSTR_TYPE_COMMON      , 6'b000011}: value = 26'b00000000000000000000000000;
			/* JALR    */  {`INSTR_TYPE_SPECIAL     , 6'b001001}: value = 26'b00000000000000000000001001;
			/* JR      */  {`INSTR_TYPE_SPECIAL     , 6'b001000}: value = 26'b00000000000000000000001000;
			/* MUL     */  {`INSTR_TYPE_SPECIAL2    , 6'b000010}: value = 26'b00000000000000000000000010;
			/* MULT    */  {`INSTR_TYPE_SPECIAL     , 6'b011000}: value = 26'b00000000000000000000011000;
			/* MULTU   */  {`INSTR_TYPE_SPECIAL     , 6'b011001}: value = 26'b00000000000000000000011001;
			/* DIV     */  {`INSTR_TYPE_SPECIAL     , 6'b011010}: value = 26'b00000000000000000000011010;
			/* DIVU    */  {`INSTR_TYPE_SPECIAL     , 6'b011011}: value = 26'b00000000000000000000011011;
			/* MFHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010000}: value = 26'b00000000000000000000010000;
			/* MTHI    */  {`INSTR_TYPE_SPECIAL     , 6'b010001}: value = 26'b00000000000000000000010001;
			/* MFLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010010}: value = 26'b00000000000000000000010010;
			/* MTLO    */  {`INSTR_TYPE_SPECIAL     , 6'b010011}: value = 26'b00000000000000000000010011;
			/* LB      */  {`INSTR_TYPE_COMMON      , 6'b100000}: value = 26'b00000000000000000000000000;
			/* LBU     */  {`INSTR_TYPE_COMMON      , 6'b100100}: value = 26'b00000000000000000000000000;
			/* LH      */  {`INSTR_TYPE_COMMON      , 6'b100001}: value = 26'b00000000000000000000000000;
			/* LHU     */  {`INSTR_TYPE_COMMON      , 6'b100101}: value = 26'b00000000000000000000000000;
			/* LW      */  {`INSTR_TYPE_COMMON      , 6'b100011}: value = 26'b00000000000000000000000000;
			/* SB      */  {`INSTR_TYPE_COMMON      , 6'b101000}: value = 26'b00000000000000000000000000;
			/* SH      */  {`INSTR_TYPE_COMMON      , 6'b101001}: value = 26'b00000000000000000000000000;
			/* SW      */  {`INSTR_TYPE_COMMON      , 6'b101011}: value = 26'b00000000000000000000000000;
			/* LWL     */  {`INSTR_TYPE_COMMON      , 6'b100010}: value = 26'b00000000000000000000000000;
			/* LWR     */  {`INSTR_TYPE_COMMON      , 6'b100110}: value = 26'b00000000000000000000000000;
			/* SWL     */  {`INSTR_TYPE_COMMON      , 6'b101010}: value = 26'b00000000000000000000000000;
			/* SWR     */  {`INSTR_TYPE_COMMON      , 6'b101110}: value = 26'b00000000000000000000000000;
			/* MFC0    */  {`INSTR_TYPE_COP0        , 6'b000000}: value = 26'b00000000000000000000000000;
			/* MTC0    */  {`INSTR_TYPE_COP0        , 6'b000100}: value = 26'b00100000000000000000000000;
			/* ERET    */  {`INSTR_TYPE_COP0        , 6'b010000}: value = 26'b10000000000000000000011000;
			/* SYSCALL */  {`INSTR_TYPE_SPECIAL     , 6'b001100}: value = 26'b00000000000000000000001100;
			/* BREAK   */  {`INSTR_TYPE_SPECIAL     , 6'b001101}: value = 26'b00000000000000000000001101;
			/* MOVN    */  {`INSTR_TYPE_SPECIAL     , 6'b001011}: value = 26'b00000000000000000000001011;
			/* MOVZ    */  {`INSTR_TYPE_SPECIAL     , 6'b001010}: value = 26'b00000000000000000000001010;
			default:      value = 26'b11111111111111111111111111;
		endcase
	end

endmodule
